rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.chef-11
  - gemfiles/Gemfile.chef-10
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.chef-10
script:
  - bundle exec rake unit
  - bundle exec rake acceptance
