rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
env:
  - CHEF_VERSION=
  - CHEF_VERSION="~> 10.16.4"
  - CHEF_VERSION="~> 10.14.4"
  - CHEF_VERSION="~> 0.10.10"
  - CHEF_VERSION="~> 0.9.18"
matrix:
  allow_failures:
    - rvm: 2.0.0
  include:
    - rvm: 2.0.0
      env: CHEF_VERSION=
