language: ruby
cache: bundler
sudo: false

before_install:
  - gem install bundler

rvm:
  - 2.1
  - 2.2

branches:
  only:
    - master

bundler_args: --jobs 7 --retry 3

gemfile: gemfiles/chefspec.gemfile

env:
  - CHEF_VERSION=master
  - CHEF_VERSION=12.8.1
  - CHEF_VERSION=12.7.2
  - CHEF_VERSION=12.6.0
  - CHEF_VERSION=12.5.1
  - CHEF_VERSION=12.4.3
  - CHEF_VERSION=12.4.0
  - CHEF_VERSION=12.3.0
  - CHEF_VERSION=12.2.1
  - CHEF_VERSION=12.1.2
  - CHEF_VERSION=12.1.1
  - CHEF_VERSION=12.1.0
  - CHEF_VERSION=12.0.3

matrix:
  fast_finish: true
  allow_failures:
    - env: CHEF_VERSION=master

