sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "chat.freenode.net#chefspec"
    use_notice: true
    skip_join: true
    template:
      - "%{message} (%{author}): %{build_url}"

bundler_args: --jobs 7 --retry 3

gemfile:
  - gemfiles/chef-11.14.0.gemfile
  - gemfiles/chef-11.16.0.gemfile
  - gemfiles/chef-12.0.0.gemfile
  - gemfiles/chef-master.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/chef-master.gemfile
