language: ruby
cache: bundler
sudo: false

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

branches:
  only:
    - master

bundler_args: --jobs 7 --retry 3

matrix:
  include:
    - rvm: 2.5.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.2.0'\""
    - rvm: 2.5.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.8.3'\""
      rvm: 2.4.3
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.7.16'\""
      rvm: 2.4.3
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.6.4'\""
      rvm: 2.4.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.5.3'\""
      rvm: 2.4.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.4.24'\""
      rvm: 2.4.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.3.42'\""
      rvm: 2.4.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.2.20'\""
      rvm: 2.4.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.1.31'\""
      rvm: 2.4.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.0.118'\""
      rvm: 2.4.2
