language: ruby
cache: bundler
sudo: false

branches:
  only:
    - master

bundler_args: --jobs 7 --retry 3

matrix:
  fast_finish: true
  include:
    - rvm: 2.2
      env: CHEF_VERSION=12.8.1
      gemfile: gemfiles/chefspec.gemfile
      before_install:
        - gem install bundler
    - rvm: 2.2
      env: CHEF_VERSION=12.8.1
      gemfile: gemfiles/chefspec.gemfile
      before_install:
        - gem update --system
        - gem install bundler

